required = ["github.com/docker/distribution/reference"]

[[constraint]]
  name = "github.com/aws/aws-sdk-go-v2"
  version = "2.0.0-preview.3"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "v0.0.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.5"

[[constraint]]
  name = "github.com/docker/docker"
  branch = "master"

[[constraint]]
  name = "github.com/docker/distribution"
  branch = "master"

#[prune]
#  go-tests = true
#  unused-packages = true
